# Synthetic Epidemiological Teaching Cohort
#
# Dataset documentation and roxygen specification for the 1,500-participant
# ESTROBE-ACS acute coronary syndrome synthetic teaching cohort.

#' ESTROBE-ACS Teaching Cohort
#'
#' A fully synthetic prospective cohort of 1,500 adults enrolled after an
#' emergency-department presentation with suspected acute coronary syndrome
#' (ACS). The data were constructed to demonstrate descriptive, design-aware,
#' diagnostic, regression, survival, sensitivity, and reporting workflows in
#' SimtablR. They do not contain real patient records.
#'
#' @details
#' ESTROBE-ACS enrolled 1,500 adult participants presenting with chest pain or
#' an ischemic equivalent and undergoing evaluation for suspected ACS.
#'
#' The primary reference diagnosis is independent clinical adjudication
#' (`adjudicated_acs`). A point-of-care high-sensitivity troponin substudy
#' (`diagnostic_substudy`) evaluated continuous troponin concentrations
#' (`poc_hstn_value`) and binary test positivity (`poc_hstn_positive`).
#'
#' In-hospital course and secondary outcomes are captured by hospital length of
#' stay (`length_of_stay`), 1-year emergency department revisits (`ed_visits`),
#' and 1-year hospital readmission (`rehospitalized`).
#'
#' Survival follow-up covers all 1,500 participants up to 365 days from
#' presentation. Major adverse cardiovascular event (MACE) status is recorded
#' by `mace_event` with follow-up time in `mace_time_days`.
#'
#' @format A data frame with 1,500 rows and 22 variables:
#' \describe{
#'   \item{participant_id}{Unique study participant identifier (`ACS0001` to `ACS1500`).}
#'   \item{age}{Age at the index presentation, in years.}
#'   \item{sex}{Sex recorded for clinical assessment (`Female`, `Male`).}
#'   \item{bmi}{Body mass index in kg/m2; contains clinical missing values.}
#'   \item{smoking}{Smoking status (`Never`, `Former`, `Current`).}
#'   \item{hypertension}{History of hypertension (`No`, `Yes`).}
#'   \item{diabetes}{History of diabetes (`No`, `Yes`).}
#'   \item{dyslipidemia}{History of dyslipidemia (`No`, `Yes`).}
#'   \item{cholesterol}{Total cholesterol in mg/dL; contains clinical missing values.}
#'   \item{presentation_hours}{Hours from symptom onset to emergency department presentation.}
#'   \item{systolic_bp}{Systolic blood pressure at presentation, in mmHg.}
#'   \item{renal_impairment}{Renal impairment (eGFR below 60 mL/min/1.73 m2; `No`, `Yes`).}
#'   \item{dialysis}{Maintenance dialysis (`No`, `Yes`); rare clinical exposure.}
#'   \item{adjudicated_acs}{Independent reference diagnosis of acute coronary syndrome (`No`, `Yes`).}
#'   \item{diagnostic_substudy}{Enrolled in point-of-care diagnostic substudy (`No`, `Yes`).}
#'   \item{poc_hstn_value}{Point-of-care high-sensitivity troponin in ng/L.}
#'   \item{poc_hstn_positive}{Binary point-of-care troponin result (`Negative`, `Positive`).}
#'   \item{length_of_stay}{Index hospital length of stay, in days.}
#'   \item{ed_visits}{Emergency department revisits during 1-year follow-up.}
#'   \item{rehospitalized}{Hospital readmission during 1-year follow-up (`No`, `Yes`).}
#'   \item{mace_time_days}{Time to MACE or censoring after presentation, in days.}
#'   \item{mace_event}{Observed major adverse cardiovascular event before censoring (`No`, `Yes`).}
#' }
#'
#' @source Synthetic data generated by `data-raw/generate-epitabl.R`.
#' @examples
#' data(epitabl)
#'
#' table1(
#'   epitabl,
#'   c(age, sex, smoking, renal_impairment),
#'   by = adjudicated_acs
#' )
#'
#' diagnostic <- subset(epitabl, diagnostic_substudy == "Yes")
#' diag_test(
#'   diagnostic,
#'   test = poc_hstn_positive,
#'   ref = adjudicated_acs,
#'   positive = "Yes"
#' )
"epitabl"
